// Autogenerated file, do not edit. To regenerate this file, please use gen.py

#ifndef EMU2_TAGS
#define EMU2_TAGS

typedef enum {

    EMU2_TAG_None = 0xffffffff,

    EMU2_TAG_BlockPriceDetail = 0x2c339ed7,
    EMU2_TAG_Channel = 0xd95dc4b3,
    EMU2_TAG_ConnectionStatus = 0xeb33e88d,
    EMU2_TAG_Currency = 0x4967ec34,
    EMU2_TAG_CurrentSummationDelivered = 0x4c1222c0,
    EMU2_TAG_Demand = 0xa90b886d,
    EMU2_TAG_Description = 0x20f66081,
    EMU2_TAG_DeviceInfo = 0xec812355,
    EMU2_TAG_DeviceMacId = 0x57f02b83,
    EMU2_TAG_DigitsLeft = 0x104c5543,
    EMU2_TAG_DigitsRight = 0xe52d7c59,
    EMU2_TAG_Divisor = 0x4f0e82b8,
    EMU2_TAG_Duration = 0x5dc5d975,
    EMU2_TAG_ExtPanId = 0x684c17c4,
    EMU2_TAG_InstantaneousDemand = 0x2aaea6ea,
    EMU2_TAG_LinkStrength = 0x0730cb6a,
    EMU2_TAG_LocalTime = 0x438eca16,
    EMU2_TAG_MeterMacId = 0xa38d0f10,
    EMU2_TAG_Multiplier = 0x5f210632,
    EMU2_TAG_NetworkInfo = 0xaf804ee8,
    EMU2_TAG_Price = 0xc93c6a29,
    EMU2_TAG_PriceCluster = 0x1c4d1da6,
    EMU2_TAG_RateLabel = 0xde0a8ccd,
    EMU2_TAG_ScheduleInfo = 0x86698ee3,
    EMU2_TAG_ShortAddr = 0xa3287d76,
    EMU2_TAG_StartTime = 0xc2717010,
    EMU2_TAG_Status = 0x5dd2b5b1,
    EMU2_TAG_SummationDelivered = 0x31485142,
    EMU2_TAG_SummationReceived = 0x7809372d,
    EMU2_TAG_SuppressLeadingZero = 0x3a768f20,
    EMU2_TAG_Tier = 0xd68fbe16,
    EMU2_TAG_TimeCluster = 0x01d13357,
    EMU2_TAG_TimeStamp = 0x20e9cd8c,
    EMU2_TAG_TrailingDigits = 0x9c965020,
    EMU2_TAG_UTCTime = 0x1e5f4927,

} Emu2Tag;

#endif

