#!/usr/bin/env python
#cat tags.txt| python gen.py > emu2_tags.h

import sys
import mmh3

SEED = 42
PREFIX = "EMU2_TAG_"

NONE_HASH = 0xffffffff

hashes = {NONE_HASH: "None"}

for tag in sys.stdin.readlines():
    t = tag.strip()
    h = mmh3.hash(t, SEED) & 0xffffffff

    if (h in hashes):
        print("Hash collision: tag {:s} has the same hash as tag {:s}".format(t, hashes.get(h)), file=sys.stderr)
        exit(1)

    hashes[h] = t

def gen_enum(h:str, tag:str, pad=4) -> str:
    return "{:s}{:s}{:s} = 0x{:08x},".format(" " * pad, PREFIX, tag, h)

print("""//This is an autogenerated file, do not edit.

#ifndef EMU2_TAGS
#define EMU2_TAGS

typedef enum {
""")

print(gen_enum(NONE_HASH, hashes.pop(NONE_HASH)))
print()

for h, t in hashes.items():
    print(gen_enum(h, t))

print("""
} Emu2Tag;

#endif
""")